openapi: 3.0.1
info:
  description: A service that matches wearable jackets for a given kitten
  version: 1.0.0
  title: Kitten Jacket Matcher Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: localhost:8080
paths:
  /kitten_jackets/{kittenId}:
    get:
      operationId: getKittenJacketsByKittenId
      parameters:
        - in: path
          name: kittenId
          description: Id of the kitten for which the user would like wearable jackets
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JacketsResponse"
        404:
          description: Not found
        500:
          description: Server error
components:
  schemas:
    JacketsResponse:
      type: object
      properties:
        total:
          type: number
          example: 1
        items:
          type: array
          items:
            $ref: "#/components/schemas/Jacket"
    Jacket:
      type: object
      properties:
        size:
          type: string
          enum:
            - S
            - M
            - L
            - XL
          example: blue
        color:
          type: string
          enum:
            - blue
            - red
            - stars
            - yellow
          example: blue
        sex:
          type: string
          enum:
            - f
            - m
            - u
          example: f